### ISSUE TITLE
Use a code for the status

### ISSUE THREAD

**Issue by duylong** [trevorndodds/elasticsearch-metrics#10]
Hi,

It will be nice to have a return code for the status in order to set a color on the dashboard.

Best regards,

**Comment by trevorndodds** [comment]
Yeah, not sure why I never did that probably in the interest of time. I'll take a look in the next week or so.

**Comment by trevorndodds** [comment]
https://github.com/trevorndodds/elasticsearch-metrics/commit/a1634d1311cf3a87557fe35ab479439f4039343e
