### ISSUE TITLE
Search Rate / Latency

### ISSUE THREAD

**Issue by duylong** [trevorndodds/elasticsearch-metrics#13]
Hi,

The keys "primaries.search.query_total" and "primaries.search.query_time_in_millis" do not have the same unit. It should not be on the same graph.

**Comment by duylong** [comment]
Same for "Indices Search" :)

**Comment by trevorndodds** [comment]
They use different Y Axis and both have different Units per Y Axis.

**Comment by trevorndodds** [comment]
Seems, the version uploaded does not have it using the Y Axis. I'll upload my new one in a few days once I add the status code related to https://github.com/trevorndodds/elasticsearch-metrics/issues/10

**Comment by duylong** [comment]
Sorry, I don't see left AND right Y
