### ISSUE TITLE
Can't connect to elasticsearch cluster with basic auth

### ISSUE THREAD

**Issue by kamenmackay** [trevorndodds/elasticsearch-metrics#20]
I recently added auth to my ELK stack using readonlyrest. Elasticsearch-metrics was working fine before the auth but won't connect anymore. Snooping through elasticsearch2elastic.py, I see that there is no code to handle a username/password combination and forward it as part of the request.

**Comment by BBQigniter** [comment]
quick and dirty

try for example at line 11:
`elasticServer = os.environ.get('ES_METRICS_CLUSTER_URL', 'http://my_basic_auth_user:my_basic_auth_password@server1:9200')`

worked for me - it is not nice and absolutely not recommended but it works :)

**Comment by keyboardfann** [comment]
Hi @kamenmackay,
     The new code has merged into the master branch, could you try the new code?

Config
```
# Enable Elasticsearch Security
es_security_enable = False
username = "username"
password = "password"
```

**Comment by keyboardfann** [comment]
Hi @kamenmackay,
The new code has merged into the master branch, could you try the new code?

Config
```
# Enable Elasticsearch Security
es_security_enable = True
read_username = "elastic"
read_password = "FvlRdh5hdb0EoZStsd8G"
write_username =  "elastic"
write_password =  "xRoCwe7LRjhtploQelne"
```

**Comment by trevorndodds** [comment]
It would be good to have an option to separate es_security enabled from both read and write. If for some reason the monitoring cluster does not use auth.

**Comment by keyboardfann** [comment]
The default es_security_enable is set to false and it will not use auth. If the user wants to collect info from one security cluster and send to another security cluster, they may use different user & password, so I separate it.

**Comment by trevorndodds** [comment]
Correct but for example my monitoring cluster doesn’t have auth yet my main cluster does. So setting a different flag for the monitoring cluster might be required.

**Comment by trevorndodds** [comment]
@keyboardfann thanks, all good now.
