### ISSUE TITLE
grafana dashboard Rev8 fail

### ISSUE THREAD

**Issue by keyboardfann** [trevorndodds/elasticsearch-metrics#29]
Hi @trevorndodds,
    I try the dashboard rev8 and fail. I also try Rev5 and works fine, could you help to check Rev8?

https://grafana.com/dashboards/878/revisions

Rev8
![image](https://user-images.githubusercontent.com/1110451/41355499-42a68dc2-6f54-11e8-9c16-26ccf3ee0f18.png)
![image](https://user-images.githubusercontent.com/1110451/41355504-44c95fda-6f54-11e8-84b9-04ddaead66d7.png)
![image](https://user-images.githubusercontent.com/1110451/41355506-46c2358c-6f54-11e8-8444-ff841b9951e9.png)

Rev5
![image](https://user-images.githubusercontent.com/1110451/41355513-4a9e8b2e-6f54-11e8-9d89-05ccb4454e98.png)
![image](https://user-images.githubusercontent.com/1110451/41355519-4e8ab8a2-6f54-11e8-9952-b542bf5879eb.png)
![image](https://user-images.githubusercontent.com/1110451/41355525-50682948-6f54-11e8-8e92-458859ea3684.png)

**Comment by trevorndodds** [comment]
Does the datasource variables look correct? I did notice that exporting from grafana 5 caused some issues.

**Comment by trevorndodds** [comment]
I tried importing again and it seems to be fine. What version of grafana are you running?

**Comment by keyboardfann** [comment]
I try it on grafana4.x. Let me confirm grafana5 and reply you tomorrow.

**Comment by trevorndodds** [comment]
how does it look on grafana 5?

**Comment by keyboardfann** [comment]
Hi @trevorndodds,
    Do you still want the latest dashboard support grafana v4?

**Comment by trevorndodds** [comment]
Hi @keyboardfann since v5 has been out for a few months I do not really see the point to support v4 too.

**Comment by keyboardfann** [comment]
OK, it's fine.
