### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by crab86** [trevorndodds/elasticsearch-metrics#34]
Why did you write an exporter yourself? Elasticsearch (as well as Logstash btw) do expose all of their metrics out-of-the-box by simply adding the following to your elasticsearch.yml (or logstash.yml):

xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

See here for [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-monitoring.html) and here for [logstash](https://www.elastic.co/guide/en/logstash/current/configuring-logstash.html). 

Afterwards you get an monitoring-es (and monitoring-logstash) index in your cluster with all of the metrics. I think this should be the way to go, because you do not need to adept your own exporter in case a new version of es or logstash comes out.

**Comment by trevorndodds** [comment]
I hear you, however this was created 2+ years ago. Back on 2.X when the metrics were not so good.  
Since all the new metrics coming from xpack these days I do not update this exporter anymore. Given you can get all of these from the xpack index you can build grafana dashboards around that.
