### ISSUE TITLE
the connect to es URL can support mulit urls?

### ISSUE THREAD

**Issue by zqc0512** [trevorndodds/elasticsearch-metrics#35]
the connect to es URL can support mulit urls?  in one cluster? when one es node down the other can use..
elasticServer = os.environ.get('ES_METRICS_CLUSTER_URL', 'http://xxxx:9200')
can support as :
elasticServer = os.environ.get('ES_METRICS_CLUSTER_URL', 'http://xxx:9200,http://xxx1:9200')

thanks.
@trevorndodds

**Comment by trevorndodds** [comment]
You could front it with a Load Balancer, HA Proxy etc.
