### ISSUE TITLE
Difference between ES_METRICS_CLUSTER_URL & ES_METRICS_MONITORING_CLUSTER_URL ?

### ISSUE THREAD

**Issue by gopi158** [trevorndodds/elasticsearch-metrics#38]
Hi All,

Can you explain what's the difference btw ES_METRICS_CLUSTER_URL & ES_METRICS_MONITORING_CLUSTER_URL  as I am little confused what should be the value for them?
As far my understanding ES_METRICS_CLUSTER_URL="http://elestic_serch_node1:9200, http://elestic_serch_node1:9200, http://elestic_serch_node1:9200" (all elesticsearch cluster nodes). Is this correct ?
Also, want to know the value for ES_METRICS_MONITORING_CLUSTER_URL="????" is it collector node URL or something else?

Thanks in advance.

**Comment by gopi158** [comment]
As we are using **https** in our cluster do we need to make a change or add code in the python script.

**Comment by trevorndodds** [comment]
Yes, you will have to add TLS support.
