### ISSUE TITLE
why we need index+date as index name

### ISSUE THREAD

**Issue by changsijay** [trevorndodds/elasticsearch-metrics#39]
Hi I saw code

`url = "%(cluster)s/%(index)s-%(index_period)s/message" % url_parameters`

wondering why we create different index for everyday metrics?
the grafana data source need to specify index name.
then the dashboard only show the metric of specific date?

**Comment by ChrisOnToure** [comment]
+1 was wondering as well since we build a dashboard on it and need to change the datasource name every day as the index name changes.

**Comment by trevorndodds** [comment]
The index rolls over daily or you can adjust it to monthly by removing the day field in the date parameter. When you create the datasource in grafana you tell it what your pattern is (daily/monthly) it takes care of using the correct index.

**Comment by changsijay** [comment]
@trevorndodds got it, thanks a lot, will try it :+1:
