### ISSUE TITLE
Can't get elasticsearch cluster stats

### ISSUE THREAD

**Issue by redhawk19** [trevorndodds/elasticsearch-metrics#40]
Hi,

I'm using following settings, when i run the script it shows HTTP error mentioned below. And I have added elasticsearch datasource in grafana too.
```
# ElasticSearch Cluster to Monitor
elasticServer = os.environ.get('ES_METRICS_CLUSTER_URL', 'http://elasticserverIP:9200')
interval = int(os.environ.get('ES_METRICS_INTERVAL', '60'))

# ElasticSearch Cluster to Send Metrics
elasticIndex = os.environ.get('ES_METRICS_INDEX_NAME', '*')
elasticMonitoringCluster = os.environ.get('ES_METRICS_MONITORING_CLUSTER_URL', 'http://elasticserverIP:9200')
```

**Error:**

```
Error:  HTTP Error 400: Bad Request
Error:  HTTP Error 400: Bad Request
Error:  HTTP Error 400: Bad Request
Error:  HTTP Error 400: Bad Request
Error:  HTTP Error 400: Bad Request
Error:  HTTP Error 400: Bad Request
Error:  HTTP Error 400: Bad Request
Total Elapsed Time: 1.16779112816
```
How could I get rid off this issue ?

Regards,
redhawk19

**Comment by diogoim** [comment]
Hi everyone,

I am getting these errors after launching the script:

Traceback (most recent call last):
  File "./elasticsearch2elastic.py", line 149, in <module>
    main()
  File "./elasticsearch2elastic.py", line 135, in main
    clusterName = fetch_clusterhealth()
  File "./elasticsearch2elastic.py", line 54, in fetch_clusterhealth
    jsonData = json.loads(response.read())
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded


Any help would be appreciated

Thanks
