### ISSUE TITLE
ESv7.0 compatibility 

### ISSUE THREAD

**Issue by anilkumar000** [trevorndodds/elasticsearch-metrics#45]
i have tried same dashboard for datasource ElasticsSearch v7.6.0. but no data is getting displayed or fetched.  Any suggestions for this? Awaiting for quick response.

**Comment by JSylvia007** [comment]
I know this is 2 years old, BUT, I finally started trying to pull this apart and I fixed it.  ONE line of code needs to be changed.

In the "elasticsearch2elastic.py" file, around line 116,:
`url = "%(cluster)s/%(index)s-%(index_period)s/message" % url_parameters`

change "message" to "_doc"

`url = "%(cluster)s/%(index)s-%(index_period)s/_doc" % url_parameters`

Seems to be working for me once again.
