### ISSUE TITLE
Node OS, Node Stat Indices, Node JVM Displaying Error

### ISSUE THREAD

**Issue by locolbd** [trevorndodds/elasticsearch-metrics#5]
All graphs on the above mentioned are not displaying data and throwing the error below.
Cannot parse name:()
    "root_cause": [
        {
            "type": "parse_exception",
            "reason": "parse_exception: Encountered \" \")\" \") \"\" at line 1, column 6.\nWas expecting one of:\n     ...\n    \"+\" ...\n    \"-\" ...\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n     ...\n    "
        }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
        {
            "shard": 0,
            "index": "elasticsearch_metrics-2017.01.27",
            "node": "Y9VfAr1aS0-QeiLEG9UmIg",
            "reason": {
                "type": "query_shard_exception",
                "reason": "Failed to parse query [name:()]",
                "index_uuid": "XoXqMb2GS0-_mcPsgESjZA",
                "index": "elasticsearch_metrics-2017.01.27",
                "caused_by": {
                    "type": "parse_exception",
                    "reason": "parse_exception: Cannot parse 'name:()': Encountered \" \")\" \") \"\" at line 1, column 6.\nWas expecting one of:\n     ...\n    \"+\" ...\n    \"-\" ...\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n     ...\n    ",
                    "caused_by": {
                        "type": "parse_exception",
                        "reason": "parse_exception: Encountered \" \")\" \") \"\" at line 1, column 6.\nWas expecting one of:\n     ...\n    \"+\" ...\n    \"-\" ...\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n     ...\n    "
                    }
                }
            }
        }
    ],
    "caused_by": {
        "type": "query_shard_exception",
        "reason": "Failed to parse query [name:()]",
        "index_uuid": "XoXqMb2GS0-_mcPsgESjZA",
        "index": "elasticsearch_metrics-2017.01.27",
        "caused_by": {
            "type": "parse_exception",
            "reason": "parse_exception: Cannot parse 'name:()': Encountered \" \")\" \") \"\" at line 1, column 6.\nWas expecting one of:\n     ...\n    \"+\" ...\n    \"-\" ...\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n     ...\n    ",
            "caused_by": {
                "type": "parse_exception",
                "reason": "parse_exception: Encountered \" \")\" \") \"\" at line 1, column 6.\nWas expecting one of:\n     ...\n    \"+\" ...\n    \"-\" ...\n     ...\n    \"(\" ...\n    \"*\" ...\n     ...\n     ...\n     ...\n     ...\n     ...\n    \"[\" ...\n    \"{\" ...\n     ...\n     ...\n    "
            }
        }
    }
}

**Comment by trevorndodds** [comment]
Check the templating settings, and ensure both cluster and nodes values are being updated for each template if null check in elasticsearch that these values are present (cluster_name/name).

**Comment by locolbd** [comment]
Thanks for your prompt response.

On templating settings:
Cluster_name
Preview of values:
istmachines

name
Preview of values:
all

I looked in elasticsearch and i do values for both
"cluster_name" : "istmachines",
"name" : "ist756"

**Comment by locolbd** [comment]
So I made some progress.  
In the templating settings i modifed
{"find": "terms", "field": "name"} to {"find": "terms", "field": "name.keyword"} and I was able to see some more data

**Comment by trevorndodds** [comment]
On 5.X you will have to change the template to use cluster_name.keyword unless you set cluster_name to not_analyzed on the index. Same for the nose names.

**Comment by locolbd** [comment]
Yes I did not know that for node name.
Please pardon my n00b question. Where do i set this fielddata=true so that the other metrics that are turned off will be displayed?

**Comment by trevorndodds** [comment]
I never had to set that. But I assume you could find that on the elasticsearch site.

**Comment by locolbd** [comment]
Cheers I will search.

Thanks for these Dashboard, you have definitely saved me a ton of time.
