### ISSUE TITLE
Can't get any Data

### ISSUE THREAD

**Issue by cooperspencer** [trevorndodds/elasticsearch-metrics#6]
Hi,

I found your dashboard and tried to make it work, but I don't really understand what you mean there:
![image](https://cloud.githubusercontent.com/assets/27288824/24913561/d199fd54-1ed1-11e7-8d12-b2fc3dbc654f.png)

Can you please help me?

**Comment by trevorndodds** [comment]
You could also edit the template setting and add .raw (v2) or .keyword (v5) to name. Then you don't need to deploy a custom index.

**Comment by PatelParas** [comment]
.raw or .keyword not working in mycase. i use v2.4.1 any suggestion ?
